apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  selector:
    matchLabels:
      app: payment-service
  replicas: 2
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: borissolomonia/dailycodebuffer:payment-service-06
          ports:
            - containerPort: 8082
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
            - name: CONFIG_SERVER_URL
              value: "http://config-server-svc:9296/"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: hostname
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
spec:
  selector:
    app: payment-service
  ports:
    - port: 80
      targetPort: 8082